spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/typeCraft
    username: dbuser
    password: dbpassword

mybatis:
  # 패키지 생략하고 클래스명만 쓸 수 있게
  type-aliases-package: com.typecraft.**.domain

  # Mapper XML 위치
  mapper-locations: classpath:mapper/**/*.xml

  configuration:
    # 스네이크 케이스 → 카멜 케이스 자동 변환
    # DB: display_order, is_active → Java: displayOrder, isActive
    map-underscore-to-camel-case: true

    # 쿼리 로그 출력
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.codeman: DEBUG
    org.mybatis: DEBUG